name: "Frontend Example"

services:
  frontend:
    container_name: frontend
    build: .
    tty: true
    ports:
      - "5000:5000"
    expose:
      - "5000"
    volumes:
      - .:/code
    environment:
      - CHOKIDAR_USEPOLLING=true
